language: java
jdk:
  - openjdk8
before_script:
  - docker login -u bitkas -p 123456789
  - docker pull openjdk:8
script:
  - ./gradlew install
  - ./gradlew jib --image bitkas/prochilddai
after_script:
  - docker pull bitkas/prochilddai

deploy:
  provider: heroku
  api_key: 0aa7d7bc-63ad-4751-9c8b-ed405db81455
  on:
    all_branches: true
  app: aqueous-waters-59160