language: java
jdk:
  - openjdk8
before_script:
  - docker login -u bitkas -p 123456789
  - docker pull openjdk:8
script:
  - ./gradlew install
  - ./gradlew jib --image bitkas/prochilddai
after_script:
  - docker pull bitkas/prochilddai

deploy:
  provider: heroku
  api_key:
    secure: 9d03bee5-aa8c-458d-9f6a-143eb947bb76
  app: aqueous-waters-59160